import { adminTableRow } from '../components/AdminTable/AdminTable'

export const tableData: adminTableRow[] = [
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 10,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 53,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 100,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 0,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 67,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 22,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 78,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100', alt: 'Imagine' },
		name: 'Proba',
		type: 'Location',
		status: 'Active',
		bookings: 5,
		rating: 0,
	},
]

export const users: adminTableRow[] = [
	{
		image: { url: 'https://i.pravatar.cc/100?u=1', alt: 'Imagine' },
		name: 'Andrei Popescu',
		type: 'User',
		status: 'Active',
		bookings: 12,
		rating: 4.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=2', alt: 'Imagine' },
		name: 'Maria Ionescu',
		type: 'User',
		status: 'Inactive',
		bookings: 5,
		rating: 3.8,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=3', alt: 'Imagine' },
		name: 'Ionel Dobre',
		type: 'User',
		status: 'Active',
		bookings: 8,
		rating: 4.2,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=4', alt: 'Imagine' },
		name: 'Elena Georgescu',
		type: 'User',
		status: 'Inactive',
		bookings: 2,
		rating: 2.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=5', alt: 'Imagine' },
		name: 'Cătălin Vasilescu',
		type: 'User',
		status: 'Active',
		bookings: 15,
		rating: 5.0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=6', alt: 'Imagine' },
		name: 'Raluca Stan',
		type: 'User',
		status: 'Active',
		bookings: 7,
		rating: 3.7,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=7', alt: 'Imagine' },
		name: 'George Marinescu',
		type: 'User',
		status: 'Inactive',
		bookings: 4,
		rating: 3.0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=8', alt: 'Imagine' },
		name: 'Ioana Nedelcu',
		type: 'User',
		status: 'Active',
		bookings: 6,
		rating: 4.0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=9', alt: 'Imagine' },
		name: 'Vlad Toma',
		type: 'User',
		status: 'Inactive',
		bookings: 3,
		rating: 2.9,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=10', alt: 'Imagine' },
		name: 'Diana Radu',
		type: 'User',
		status: 'Active',
		bookings: 10,
		rating: 4.1,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=11', alt: 'Imagine' },
		name: 'Mihai Enache',
		type: 'User',
		status: 'Inactive',
		bookings: 1,
		rating: 2.0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=12', alt: 'Imagine' },
		name: 'Ana Tudor',
		type: 'User',
		status: 'Active',
		bookings: 13,
		rating: 4.8,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=13', alt: 'Imagine' },
		name: 'Cristian Ilie',
		type: 'User',
		status: 'Active',
		bookings: 9,
		rating: 3.9,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=14', alt: 'Imagine' },
		name: 'Laura Nistor',
		type: 'User',
		status: 'Active',
		bookings: 11,
		rating: 4.3,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=15', alt: 'Imagine' },
		name: 'Bogdan Munteanu',
		type: 'User',
		status: 'Inactive',
		bookings: 0,
		rating: 0.0,
	},
]

export const groups: adminTableRow[] = [
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup1', alt: 'Imagine grup' },
		name: 'Echipa Veselă',
		type: 'Grup',
		status: 'Active',
		bookings: 12,
		rating: 4.3,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup2', alt: 'Imagine grup' },
		name: 'Sunset Explorers',
		type: 'Grup',
		status: 'Inactive',
		bookings: 5,
		rating: 3.9,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup3', alt: 'Imagine grup' },
		name: 'Sea Squad',
		type: 'Grup',
		status: 'Active',
		bookings: 8,
		rating: 4.1,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup4', alt: 'Imagine grup' },
		name: 'Grupul Relaxare',
		type: 'Grup',
		status: 'Inactive',
		bookings: 3,
		rating: 3.2,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup5', alt: 'Imagine grup' },
		name: 'Party People',
		type: 'Grup',
		status: 'Active',
		bookings: 10,
		rating: 4.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup6', alt: 'Imagine grup' },
		name: 'Ocean Crew',
		type: 'Grup',
		status: 'Inactive',
		bookings: 7,
		rating: 3.7,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup7', alt: 'Imagine grup' },
		name: 'The Sandstormers',
		type: 'Grup',
		status: 'Active',
		bookings: 15,
		rating: 4.8,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup8', alt: 'Imagine grup' },
		name: 'Valurile Verii',
		type: 'Grup',
		status: 'Active',
		bookings: 11,
		rating: 4.0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup9', alt: 'Imagine grup' },
		name: 'Coasta Cool',
		type: 'Grup',
		status: 'Inactive',
		bookings: 2,
		rating: 2.8,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup10', alt: 'Imagine grup' },
		name: 'Summer Tribe',
		type: 'Grup',
		status: 'Active',
		bookings: 9,
		rating: 4.2,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup11', alt: 'Imagine grup' },
		name: 'Nisip și Vibes',
		type: 'Grup',
		status: 'Inactive',
		bookings: 4,
		rating: 3.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup12', alt: 'Imagine grup' },
		name: 'Wave Chasers',
		type: 'Grup',
		status: 'Active',
		bookings: 13,
		rating: 4.6,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup13', alt: 'Imagine grup' },
		name: 'Litoral Legends',
		type: 'Grup',
		status: 'Active',
		bookings: 6,
		rating: 4.0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup14', alt: 'Imagine grup' },
		name: 'All Inclusive Crew',
		type: 'Grup',
		status: 'Inactive',
		bookings: 1,
		rating: 2.1,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup15', alt: 'Imagine grup' },
		name: 'Sun & Fun',
		type: 'Grup',
		status: 'Active',
		bookings: 14,
		rating: 4.9,
	},
]
