import { adminTableRow } from '../components/AdminTable/AdminTable'

export const tableData: adminTableRow[] = [
	{
		image: { url: 'https://i.pravatar.cc/100?u=12', alt: 'Imagine' },
		name: 'Magic Alexandru',
		type: 'Location',
		status: 'Active',
		bookings: 10,
		rating: 4.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=9', alt: 'Imagine' },
		name: 'BT Arena',
		type: 'Location',
		status: 'Active',
		bookings: 53,
		rating: 5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=1', alt: 'Imagine' },
		name: 'Didi jr',
		type: 'Location',
		status: 'Active',
		bookings: 100,
		rating: 0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=69', alt: 'Imagine' },
		name: 'UAIC teren',
		type: 'Location',
		status: 'Active',
		bookings: 0,
		rating: 1,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=71', alt: 'Imagine' },
		name: 'Un teren',
		type: 'Location',
		status: 'Active',
		bookings: 67,
		rating: 0,
	},
]

export const users: adminTableRow[] = [
	{
		image: { url: 'https://i.pravatar.cc/100?u=1', alt: 'Imagine' },
		name: 'Andrei Popescu',
		type: 'User',
		status: 'Active',
		bookings: 12,
		rating: 4.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=2', alt: 'Imagine' },
		name: 'Maria Ionescu',
		type: 'User',
		status: 'Inactive',
		bookings: 5,
		rating: 3.8,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=3', alt: 'Imagine' },
		name: 'Ionel Dobre',
		type: 'User',
		status: 'Active',
		bookings: 8,
		rating: 4.2,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=4', alt: 'Imagine' },
		name: 'Elena Georgescu',
		type: 'User',
		status: 'Inactive',
		bookings: 2,
		rating: 2.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=5', alt: 'Imagine' },
		name: 'Cătălin Vasilescu',
		type: 'User',
		status: 'Active',
		bookings: 15,
		rating: 5.0,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=6', alt: 'Imagine' },
		name: 'Raluca Stan',
		type: 'User',
		status: 'Active',
		bookings: 7,
		rating: 3.7,
	},
]

export const groups: adminTableRow[] = [
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup1', alt: 'Imagine grup' },
		name: 'Echipa Veselă',
		type: 'Grup',
		status: 'Active',
		bookings: 12,
		rating: 4.3,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup2', alt: 'Imagine grup' },
		name: 'Sunset Explorers',
		type: 'Grup',
		status: 'Inactive',
		bookings: 5,
		rating: 3.9,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup3', alt: 'Imagine grup' },
		name: 'Sea Squad',
		type: 'Grup',
		status: 'Active',
		bookings: 8,
		rating: 4.1,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup4', alt: 'Imagine grup' },
		name: 'Grupul Relaxare',
		type: 'Grup',
		status: 'Inactive',
		bookings: 3,
		rating: 3.2,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup5', alt: 'Imagine grup' },
		name: 'Party People',
		type: 'Grup',
		status: 'Active',
		bookings: 10,
		rating: 4.5,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup6', alt: 'Imagine grup' },
		name: 'Ocean Crew',
		type: 'Grup',
		status: 'Inactive',
		bookings: 7,
		rating: 3.7,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup7', alt: 'Imagine grup' },
		name: 'The Sandstormers',
		type: 'Grup',
		status: 'Active',
		bookings: 15,
		rating: 4.8,
	},
	{
		image: { url: 'https://i.pravatar.cc/100?u=grup8', alt: 'Imagine grup' },
		name: 'Valurile Verii',
		type: 'Grup',
		status: 'Active',
		bookings: 11,
		rating: 4.0,
	},
]
